name: Checks

on:
  pull_request:
  push:
    branches: [master]

jobs:
  checks:
    uses: kaisekidev/.github/.github/workflows/checks.yml@v1
    with:
      run-tests: false   # no tests yet; static analysis only (variant A)
